version: latest
services:
  redis:
    image: redis:7.2.3
    ports:
      - "6379:6379"
    volumes:

  app:
    build: .
    ports:
      - "8028:8028"
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
  volumes:
    redis_data: